### ISSUE TITLE
Migrate to Vega2

### ISSUE THREAD

**Issue by randyzwitch** [johnmyleswhite/Vega.jl#11]
Given the new major release of [Vega](http://vega.github.io/vega/), let's migrate to Vega 2. Here's how I see it working out for just migration (i.e. no new features unless the come naturally during migration)

- [x] ~~Swap out the vega.js libraries for vega2 for REPL~~
- [x] ~~Modify Julia type system to match Vega2 changes~~ Committed to vega2 branch as best as I could tell
- [x] Migrate remaining graphs
    * ~~choropleth~~
    * ~~groupedbar~~
    * ~~popchart~~
    * ~~wordcloud (Told by Vega folks that this will be included in coming week release)~~
    * ~~Fix pie chart calculation~~
    * ~~Update [heatmap to Vega2 example](http://vega.github.io/vega-editor/index.html?spec=heatmap)~~ 
- [x] ~~Migrate all mutating functions (All functions worked without modification!)~~
- [x] Work through existing API, making existing graphing and mutating functions as buttoned-up as possible (i.e. fixes like #9) - TOO GENERIC
- [x] ~~Make plots work in Notebook (prior code stripped out, will seek help from somewhere)~~ Moved to #16 
- [x] Pick a default color scheme (ordinal10 is harsh) #19 
- [x] Write proper tests, make Vega.jl pass like a real Julia library (clean out current cruft) #20 

After swapping out the existing library and making sure all existing functionality works, then enhancements can resume (see [README.md](https://github.com/johnmyleswhite/Vega.jl/blob/master/README.md)).

**Comment by spencerlyon2** [comment]
I've made _some_ progress. Two things that needed to happen were:

1. remove `data.` prefix in all `VegaDataRef` types
2. Change `keys` to `groupby` in the `facet` transform for making lines and such different colors. 

They are on my fork of the `vega2` branch

**Comment by spencerlyon2** [comment]
For the first point above, do you want to think about having vega2 as a submodule? I've always regretted times when I've used  submodules, but they do seem like the right tool in this case.

**Comment by randyzwitch** [comment]
I'm indifferent, but like you, I don't like them personally. Vega used to be a submodule, but it allows for the weird scenario if someone does an update against the submodule, breaks the Julia code, and then wants a Julia update. 

Do you want to submit a PR for the first task, so I don't have to migrate in the library myself? Or did you just hack it into place for testing?

**Comment by spencerlyon2** [comment]
Hey sorry for the delay. I can submit a PR.

A word of warning: after merging those changes nothing will work because vega 1 js is still being loaded in `render.jl`. I did hack a local change to load new js on my machine, but I think finding a solution to point 1 above will take care of that issue in a better way.

**Comment by spencerlyon2** [comment]
As we work through mapping Vega "types" to Julia types, do we want to do all of them?

I guess what I am asking is should we do things like `cross`, `filter`, `fold`, `facet`, etc from the [data transforms](https://github.com/vega/vega/wiki/Data-Transforms#-stack) page. 

I think it would be great to have a native representation of all these different components of a vega spec. 

If you are on board then I can start working through that page of the docs and adding all the types. Because there are so many I'd either put them all into `src/primitives/transforms.jl` or do something like `src/primitives/transforms/(cross|filter|fold|facet).jl`

**Comment by randyzwitch** [comment]
I think the answer is yes, we should match the type spec exactly. Before you start working on this, let me get the Notebook PR in, so that we can check off the first task. Then we can go through the types, figure out which one's need to be deprecated/changes due to the new spec and which ones need to be added.

**Comment by randyzwitch** [comment]
Looks like the inline Notebook plots is going to be harder than I expected. It works perfectly for the current published version of Vega.jl, but switching to our vega2 branch it gives me an 'undefined' error which I can't track down.

**Comment by spencerlyon2** [comment]
I had the same problem....

Whether I included a locally built version or linked to the github url (like for the repl ) and neither worked.

**Comment by spencerlyon2** [comment]
I don't know enough javascript to know if this is an issue, but could it be a problem that we are injecting the d3 and Vega source into the output of the cell we run instead of in the <head> tag of the entire notebook?

**Comment by spencerlyon2** [comment]
Looks like that shouldn't be the problem: http://www.w3schools.com/js/js_whereto.asp

**Comment by randyzwitch** [comment]
I'll ask the Vega folks what might have changed. In the meantime, we can work from the REPL.

**Comment by randyzwitch** [comment]
Down to wordcloud as the last visualization to move over! Have a question on whether it will actually be supported in vega 2 on their mailing list, so if it's not supported, I'll factor that code out into a separate package. If it is, then I'll fix it and we'll be done the migration task.

**Comment by spencerlyon2** [comment]
Awesome!

Did they respond about the issue in the notebook?

**Comment by randyzwitch** [comment]
Didn't contact them about the notebook, I figured I'd try and work that myself before asking, since it's a super corner case (IJulia? Jupyter? Vega?)

**Comment by randyzwitch** [comment]
Geez, been over a month since I've done any development. Going to work on wordcloud, which will be a breaking change (they made a transform now, so you can just pass raw text, no need to calculate counts).

Then hopefully I can do the heatmap quickly, close out this issue, and make a new version of Vega.jl available.

**Comment by randyzwitch** [comment]
Calling this done, will move to smaller tasks in issues list, to avoid having issues that can't be resolved in 1-2 PR.
