### ISSUE TITLE
[meta] Improve Layering

### ISSUE THREAD

**Issue by randyzwitch** [johnmyleswhite/Vega.jl#143]
#142 improved upon the `layer(v1, v2)` function, but it still could use some work. This issue will track the layering of multiple series on a single X-Y axis. Inset plots or facets of plots can be a separate focus.
- [ ]  Get color support working better (i.e. how to update single series, update legend globally, etc.)
- [ ]  Test likely combinations, modify layer function to handle commonly used overlays
- [ ]  [optional] Create mutating functions for common overlays, such as regression lines (#53), distributions, rugplots, etc.
