### ISSUE TITLE
[Meta issue] Scale types/broken graphs from input data

### ISSUE THREAD

**Issue by randyzwitch** [johnmyleswhite/Vega.jl#87]
If you find a graph doesn't work, please add it here for easier tracking. A lot issues probably stem from the same basic issue of recognizing the scale data types properly (```linear, ordinal, log, sqrt, pow, quantize, quantile, time and utc```)

- [ ] Support `vector of vectors` data type (or document that "long data" is preferred/requirement) #32 
- [ ] Determine scale types by looking at Julia type and/or "sniffing" first 10-100 rows of data #61 
- [x] Line graph doesn't support time series #80 
- [x] Heatmap example from vega.js isn't particularly robust #84 #86

**Comment by randyzwitch** [comment]
The problem as I see it is two/three branches of data cleanliness/differences:

- Arrays with a firm Julia type such as `Array{Int}` or `Array{Date}`. These should be easy to check for and write subsequent rules
- `Nullable` arrays: I presume these work with the package, since all functions use an `AbstractVector` type, though I haven't tried yet
-  `Array{Any}` arrays will be most difficult, these will need to have type inferred. 

Alternatively, could have scale types as a keyword argument, but that feels hacky.

**Comment by randyzwitch** [comment]
See also #107

**Comment by randyzwitch** [comment]
The longer this stays open, the more I think that it is really the work of JSON.jl to serialize the data correctly, and most graphs only work with a certain type of data.

Until bugs come in from other people, closing this as "fixed"
